// Main entry point for the package
export * from './lib/horizon-auth.module';
export * from './lib/horizon-auth-config.interface';
export * from './auth/auth.service';
export * from './auth/auth.module';
export * from './common/decorators/public.decorator';
export * from './common/decorators/current-user.decorator';
export * from './common/decorators/roles.decorator';
export * from './common/decorators/current-tenant.decorator';
export * from './auth/guards/jwt-auth.guard';
export * from './auth/guards/roles.guard';
export * from './users/users.service';
export * from './auth/dto/register.dto';
export * from './auth/dto/login.dto';
export * from './auth/dto/password-reset.dto';

// Enhanced authentication features
export * from './two-factor/two-factor.service';
export * from './two-factor/two-factor.module';
export * from './two-factor/dto';
export * from './devices/device.service';
export * from './devices/device.module';
export * from './devices/dto';
export * from './push-tokens/push-token.service';
export * from './push-tokens/push-token.module';
export * from './push-tokens/dto';
export * from './account/account.service';
export * from './account/account.module';
export * from './account/dto';
export * from './social-auth/social-auth.service';
export * from './social-auth/social-auth.module';
export * from './social-auth/dto';
